//mutation
const SET_COMMENT_MV = "SET_COMMENT_MV";
const SET_COMMENT_MV_REFRESH = "SET_COMMENT_MV_REFRESH";
const SET_MV_COMMENT_PAGINATION = "SET_MV_COMMENT_PAGINATION";
const SET_COMMENT_PLAYLIST = "SET_COMMENT_PLAYLIST";
const SET_COMMENT_PLAYLIST_REFRESH = "SET_COMMENT_PLAYLIST_REFRESH";
const SET_PLAYLIST_COMMENT_PAGINATION = "SET_PLAYLIST_COMMENT_PAGINATION";
const RESET_COMMNET = "RESET_COMMNET";
const SET_COMMENT_VIDEO = "SET_COMMENT_VIDEO";
const SET_COMMENT_VIDEO_REFRESH = "SET_COMMENT_VIDEO_REFRESH";
const SET_COMMENT_VIDEO_PAGINATION = "SET_COMMENT_VIDEO_PAGINATION";

//action
const FETCH_COMMENT_MV = "FETCH_COMMENT_MV";
const FETCH_COMMENT_VIDEO = "FETCH_COMMENT_VIDEO";
const FETCH_COMMENT_PLAYLIST = "FETCH_COMMENT_PLAYLIST";
const FETCH_COMMENT_CURRENT = "FETCH_COMMENT_CURRENT";

export {
  FETCH_COMMENT_CURRENT,
  SET_COMMENT_VIDEO_PAGINATION,
  SET_COMMENT_VIDEO,
  FETCH_COMMENT_VIDEO,
  SET_COMMENT_MV,
  FETCH_COMMENT_MV,
  SET_MV_COMMENT_PAGINATION,
  FETCH_COMMENT_PLAYLIST,
  SET_COMMENT_PLAYLIST,
  SET_PLAYLIST_COMMENT_PAGINATION,
  RESET_COMMNET,
  SET_COMMENT_MV_REFRESH,
  SET_COMMENT_PLAYLIST_REFRESH,
  SET_COMMENT_VIDEO_REFRESH,
};
