//mutation
const SET_PERSONALIZED = "SET_PERSONALIZED";
const SET_PERSONALIZED_NEWSONG = "SET_PERSONALIZED_NEWSONG";

const SET_PERSONALIZED_MV = "SET_PERSONALIZED_MV";
const SET_BANNER = "SET_BANNER";
const SET_DISCOVER_LOADING = "SET_DISCOVER_LOADING";

//action
const FETCH_DISCOVER_ASYNC = "FETCH_DISCOVER_ASYNC";

export {
  SET_PERSONALIZED,
  SET_PERSONALIZED_NEWSONG,
  SET_PERSONALIZED_MV,
  SET_BANNER,
  FETCH_DISCOVER_ASYNC,
  SET_DISCOVER_LOADING,
};
