//mutation
const SET_MV_DETAIL = "SET_MV_DETAIL";
const SET_VIDEO_DETAIL = "SET_VIDEO_DETAIL";
const SET_MVDETAIL_LOADING = "SET_MVDETAIL_LOADING";

//action
const FTECH_MV_DETAIL = "FTECH_MV_DETAIL";
const FETCH_VIDEO_DETAIL = "FETCH_VIDEO_DETAIL";

export {
  SET_MV_DETAIL,
  SET_VIDEO_DETAIL,
  SET_MVDETAIL_LOADING,
  FTECH_MV_DETAIL,
  FETCH_VIDEO_DETAIL,
};
