//mutation
const SET_MVALL_AREA = "SET_MVALL_AREA";
const SET_MVALL_TYPE = "SET_MVALL_TYPE";
const SET_MVALL_ORDER = "SET_MVALL_ORDER";
const SET_MV_ALL = "SET_MV_ALL";
const SET_MVALL_LOADING = "SET_MVALL_LOADING";
const SET_MVALL_OFFSET = "SET_MVALL_OFFSET";
//action
const FETCH_MV_ALL = "FETCH_MV_ALL";

export {
  SET_MVALL_AREA,
  SET_MVALL_TYPE,
  SET_MVALL_ORDER,
  SET_MV_ALL,
  SET_MVALL_LOADING,
  SET_MVALL_OFFSET,
  FETCH_MV_ALL,
};
