//mutation
const SET_HOT_TAG = "SET_HOT_TAG";
const SET_All_TAG = "SET_All_TAG";
const SET_PLAYLISTS = "SET_PLAYLISTS";
const SET_PLAYLISTS_LOADING = "SET_PLAYLISTS_LOADING";
const SET_PLAYLISTS_DETAIL = "SET_PLAYLISTS_DETAIL";
const SELECTED_CURRENT_TAG = "SELECTED_CURRENT_TAG";
const SET_PLAYLIST_PAGINATION = "SET_PLAYLIST_PAGINATION";
//action
const FETCH_PLAYLIST_INITIAL_ASYNC = "FETCH_INITIAL_ASYNC";
const FETCH_UPDATE_PLAYLIST_ASYNC = "FETCH_UPDATE_PLAYLIST_ASYNC";
const FETCH_PLAYLIST_DETAIL_ASYNC = "FETCH_PLAYLIST_DETAIL_ASYNC";
const FETCH_PLAYLIST_SUBCRIBE_ASYNC = "FETCH_PLAYLIST_SUBCRIBE_ASYNC";

export {
  SET_HOT_TAG,
  SET_All_TAG,
  FETCH_PLAYLIST_INITIAL_ASYNC,
  SET_PLAYLISTS,
  SET_PLAYLISTS_LOADING,
  SELECTED_CURRENT_TAG,
  SET_PLAYLIST_PAGINATION,
  FETCH_UPDATE_PLAYLIST_ASYNC,
  FETCH_PLAYLIST_DETAIL_ASYNC,
  SET_PLAYLISTS_DETAIL,
  FETCH_PLAYLIST_SUBCRIBE_ASYNC,
};
