//mutation
const INIT_PLAYER = "INIT_PLAYER";
const PUSH_SONGS = "PUSH_SONGS";
const PUSH_SONG = "PUSH_SONG";
const CHECK_SONG = "CHECK_SONG";
const TOADD_SONG = "TOADD_SONG";
const CLEAR_SONGS = "CLEAR_SONGS";
const DEL_SONG = "DEL_SONG";
const SET_CURRENT_LYRIC = "SET_CURRENT_LYRIC";

//action
const FETCH_SONG_ASYNC = "FETCH_SONG_ASYNC";
const FETCH_SONGS_ASYNC = "FETCH_SONGS_ASYNC";

export {
  PUSH_SONGS,
  PUSH_SONG,
  CHECK_SONG,
  TOADD_SONG,
  CLEAR_SONGS,
  INIT_PLAYER,
  DEL_SONG,
  SET_CURRENT_LYRIC,
  FETCH_SONG_ASYNC,
  FETCH_SONGS_ASYNC,
};
