//mutation
const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
const PUSH_SEARCH_HISTORY = "PUSH_SEARCH_HISTORY";
const CLEAN_SEARCH_HISTORY = "CLEAN_SEARCH_HISTORY";
const DELETE_SEARCH_TAG = "DELETE_SEARCH_TAG";
const SET_SEARCH_HOT_TAGS = "SET_SEARCH_HOT_TAGS";
const ORDER_SEARCH_HISTORY = "ORDER_SEARCH_HISTORY";
const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
const SET_SEARCH_KEYWORDS_DATAS = "SET_SEARCH_KEYWORDS_DATAS";
const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
const SET_SEARCH_OFFSET = "SET_SEARCH_OFFSET";
//action
const FETCH_SEARCH_HOT_TAG_ASYNC = "FETCH_SEARCH_HOT_TAG_ASYNC";
const FETCH_SEARCH_KEYWORDS_ASYNC = "FETCH_SEARCH_KEYWORDS_ASYNC";
export {
  SET_SEARCH_OFFSET,
  SET_SEARCH_LOADING,
  SET_SEARCH_TYPE,
  SET_SEARCH_KEYWORD,
  PUSH_SEARCH_HISTORY,
  CLEAN_SEARCH_HISTORY,
  SET_SEARCH_HOT_TAGS,
  DELETE_SEARCH_TAG,
  ORDER_SEARCH_HISTORY,
  FETCH_SEARCH_HOT_TAG_ASYNC,
  FETCH_SEARCH_KEYWORDS_ASYNC,
  SET_SEARCH_KEYWORDS_DATAS,
};
