//mutation
const SET_SINGER_AREA = "SET_SINGER_AREA";
const SET_SINGER_TYPE = "SET_SINGER_TYPE";
const SET_SINGER_INITIAL = "SET_SINGER_INITIAL";
const SET_SINGER_PAGINATION = "SET_SINGER_PAGINATION";
const SET_SINGER_LIST = "SET_SINGER_LIST";
const SET_SINGER_LIST_MORE = "SET_SINGER_LIST_MORE";
const SET_SINGER_DETAIL = "SET_SINGER_DETAIL";
const SET_SINGER_ALBUM_SONGS = "SET_SINGER_ALBUM_SONGS";
const SET_SINGER_LIST_LOADING = "SET_SINGER_LIST_LOADING";
//action
const SINGER_LIST_ASYNC = "SINGER_LIST_ASYNC";
const SINGER_DETAIL_ASYNC = "SINGER_DETAIL_ASYNC";
const SINGER_ALBUM_SONGS_ASYNC = "SINGER_ALBUM_SONGS_ASYNC";
const SINGER_ALBUM_SUBSCRIBE_ASYNC = "SINGER_ALBUM_SUBSCRIBE_ASYNC";

//gutter
const IS_LOADING_ALBUM = "IS_LOADING_ALBUM";

export {
  SET_SINGER_LIST_LOADING,
  SET_SINGER_AREA,
  SET_SINGER_TYPE,
  SET_SINGER_INITIAL,
  SET_SINGER_PAGINATION,
  SET_SINGER_LIST,
  SET_SINGER_LIST_MORE,
  SET_SINGER_DETAIL,
  SET_SINGER_ALBUM_SONGS,
  SINGER_LIST_ASYNC,
  SINGER_DETAIL_ASYNC,
  SINGER_ALBUM_SONGS_ASYNC,
  SINGER_ALBUM_SUBSCRIBE_ASYNC,
  IS_LOADING_ALBUM,
};
