//getter
const FILTER_HAS_TOPLISTTYPE = "FILTER_HAS_TOPLISTTYPE";
const FILTER_NOT_HAS_TOPLISTTYPE = "FILTER_NOT_HAS_TOPLISTTYPE";

//mutation
const SET_TOPLIST_NAVBAR = "SET_TOPLIST_NAVBAR";
const SET_TOPLIST_PLAYLIST_DETAIL = "SET_TOPLIST_PLAYLIST_DETAIL";
const SET_TOPLIST_LOADING = "SET_TOPLIST_LOADING";
//action

const FETCH_TOPLIST_NAVBAR = "FETCH_TOPLIST_NAVBAR";
const FETCH_TOPLIST_PLAYLIST_DETAIL = "FETCH_TOPLIST_PLAYLIST_DETAIL";

export {
  FETCH_TOPLIST_NAVBAR,
  SET_TOPLIST_NAVBAR,
  FILTER_HAS_TOPLISTTYPE,
  FILTER_NOT_HAS_TOPLISTTYPE,
  FETCH_TOPLIST_PLAYLIST_DETAIL,
  SET_TOPLIST_LOADING,
  SET_TOPLIST_PLAYLIST_DETAIL,
};
