//mutation
const SET_USER_LOGIN = "SET_USER_LOGIN";
const SET_USER_CLEAN_PROFILE = "SET_USER_CLEAN_PROFILE";
const SET_USER_LOGIN_FAILD = "SET_USER_LOGIN_FAILD";
const SET_USER_DETAIL_LOADING = "SET_USER_DETAIL_LOADING";
const SET_USER_DETAIL = "SET_USER_DETAIL";
const SET_USER_RECORD = "SET_USER_RECORD";
const SET_USER_PLAYLIST = "SET_USER_PLAYLIST";

//actions
const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN";
const REQUEST_USER_LOGOUT = "REQUEST_USER_LOGOUT";
const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";
const FETCH_USER_RECORD = "FETCH_USER_RECORD";
const FETCH_USER_PLAYLIST = "FETCH_USER_PLAYLIST";

export {
  FETCH_USER_PLAYLIST,
  SET_USER_PLAYLIST,
  SET_USER_RECORD,
  FETCH_USER_RECORD,
  SET_USER_DETAIL,
  SET_USER_DETAIL_LOADING,
  FETCH_USER_DETAIL,
  REQUEST_USER_LOGIN,
  SET_USER_CLEAN_PROFILE,
  SET_USER_LOGIN,
  REQUEST_USER_LOGOUT,
  SET_USER_LOGIN_FAILD,
};
