//mutation
const SET_VIDEO_GROUP_TAGS = "SET_VIDEO_GROUP_TAGS";
const SET_VIDEO_CATEGORY_TAGS = "SET_VIDEO_CATEGORY_TAGS";
const SET_VIDEO_GROUP = "SET_VIDEO_GROUP";
const SET_VIDEO_LOADING = "SET_VIDEO_LOADING";
const SET_VIDEO_CURRENT_ID = "SET_VIDEO_CURRENT_ID";
const SET_VIDEO_GROUP_OFFSET = "SET_VIDEO_GROUP_OFFSET";
const SET_VIDEO_DETAIL_LOADING = "SET_VIDEO_DETAIL_LOADING";

//action
const FETCH_VIDEO_INIT = "FETCH_VIDEO_INIT";
const FETCH_VIDEO_GROUP = "FETCH_VIDEO_GROUP";

// const FETCH_TOPLIST_PLAYLIST_DETAIL = "FETCH_TOPLIST_PLAYLIST_DETAIL";

export {
  SET_VIDEO_DETAIL_LOADING,
  SET_VIDEO_CURRENT_ID,
  SET_VIDEO_GROUP_OFFSET,
  SET_VIDEO_GROUP_TAGS,
  SET_VIDEO_CATEGORY_TAGS,
  SET_VIDEO_GROUP,
  FETCH_VIDEO_INIT,
  FETCH_VIDEO_GROUP,
  SET_VIDEO_LOADING,
};
